# Site settings
title: Steffen Skov
description: A blog about C# programming and development.
url: https://steffenskov.github.io
baseurl: "/blog"
permalink: /:title/

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: csharp

# Build settings
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Code highlighting
highlighter: rouge
rouge:
  plugins:
    - rouge-plugins-csharp

# Exclude files from processing
exclude:
  - vendor

# Pagination
paginate: 5
paginate_path: "/page/:num/"

# Categories and tags
default_category: General
category_dir: category
tag_dir: tag

