# Site settings
title: Steffen Skov
description: A blog about C# programming and development.
url: https://steffenskov.github.io
baseurl: "/blog"
permalink: /:title/

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: csharp

# Build settings
theme: minima # You can replace this with the Jekyll theme of your choice
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  # Add any other plugins you might need

# Code highlighting
highlighter: rouge
rouge:
  plugins:
    - rouge-plugins-csharp

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  # Add any other exclusions you need

# Pagination
paginate: 5
paginate_path: "/page/:num/"

# Categories and tags
default_category: General
category_dir: category
tag_dir: tag
